### ISSUE TITLE
3.2 Warenpost International

### ISSUE THREAD

**Issue by ixopo** [christoph-schaeffer/dhl-business-shipping#19]
Hi Christoph, thank you very much for your awesome package!
On 21.01.2022 DHL Entwicklerportal announced the Rollout ouf 3.2.0
Ankündigungen - Geschäftskunden API 3.2.0 Rollout / Business Customer Shipment API 3.2.0.
Looks like the main Change is "Warenpost International" only ?
Will it be compatible with your version of the package 3.1.2 and later or will there be a update of your package ?

**Comment by christoph-schaeffer** [comment]
Hello @ixopo,

thanks for using the library aswell :-) 

im aware of the new version and i will update the library soon, however i want to make some bigger changes while i do that . 


Im pretty sure it will work just fine even if you use the 3.1.2 version of this library, since there aren't really many changes. At least it has been this way in the past with 3.0->3.1

**Comment by christoph-schaeffer** [comment]
@ixopo the 3.2.0 update is now released

closing the issue because it has been resolved
