### ISSUE TITLE
International shipping

### ISSUE THREAD

**Issue by wolfgangmauer** [christoph-schaeffer/dhl-business-shipping#5]
First of all "Great job!!!"

With international shipping where i can put the "V53VV" ?

Hinweis für den internationalen Versand:
Die Vorausverfügung ist ein Servicetyp (Produkt-Code V53VV), der bei
internationalen Sendungen nun eine Pflichtangabe ist und verpflichtend mit angelegt werden muss.

**Comment by wolfgangmauer** [comment]
Need more help, shipping to switzerland ...
![grafik](https://user-images.githubusercontent.com/27953724/115443640-c9e15c00-a213-11eb-9593-90d83306ed7c.png)

    $shipmentOrder1->Shipment->ExportDocument->exportType = ExportDocument::EXPORT_TYPE_OTHER;
    $shipmentOrder1->Shipment->ExportDocument->exportTypeDescription = "Handelsware";
    $shipmentOrder1->Shipment->ExportDocument->termsOfTrade = ExportDocument::TERMS_OF_TRADE_DELIVERY_DUTY_PAID;
    $shipmentOrder1->Shipment->ExportDocument-> ?????????

**Comment by christoph-schaeffer** [comment]
Hello @wolfgangmauer,

thank you for using the library and your feedback! :-) 

"V53VV" seems to be a product code, however i've never used that code. As far as i know International shipping should be "V54EPAK" for europe and "V53WPAK" for worldwide shipping. I'm not sure if you need worldwide shipping for switzerland though... Those products have different prices as well. If you want to use "V53VV" nonetheless you can set it here:

`$shipmentOrder1->Shipment->ShipmentDetails->product = "V53VV"`

for the other types (V54EPAK and V53WPAK) you could use the constants defined in ShipmentDetails
`$shipmentOrder1->Shipment->ShipmentDetails->product = ShipmentDetails::PRODUCT_INTERNATIONAL`
`$shipmentOrder1->Shipment->ShipmentDetails->product = ShipmentDetails::PRODUCT_EUROPE`

You could also contact DHL if you have a "Geschäftskunden-Portal" account. Usually you will have a designated contact person there. They should be able to tell you which product you actually should use, since like i've said these products have different pricing policy. There are multiple products for international shipping and even for national shipping.

"Vorausverfügung" seems to be the service "Endorsment". Services each have their own object in the library. here is an example how to add it:
`$shipmentOrder1->Shipment->ShipmentDetails->Service->Endorsement = Endorsement:: INTERNATIONAL_AFTER_DEADLINE `
Feel free to check the [documentation](https://christoph-schäffer.de/dhl-business-shipping/documentation/3-0/#Service) for further information

**Comment by wolfgangmauer** [comment]
If I understand correctly, V54EPAK is only for business customers, otherwise you have to use V53WPAK.

**Comment by wolfgangmauer** [comment]
For international the 
Endorsement->type
must be 
Endorsement::INTERNATIONAL_RETURN_IMMEDIATELY
