### ISSUE TITLE
[FR] Add Tracking functionality

### ISSUE THREAD

**Issue by wolfgangmauer** [christoph-schaeffer/dhl-business-shipping#9]
It would be nice to get tracking information, so as not to use multiple api's

**Comment by christoph-schaeffer** [comment]
Hello again @wolfgangmauer,

I am alrrady planning to create a lib for the dhl tracking api, however creating shipments and tracking them have esch their own dhl api. For example the shipment creation uses SOAP and the tracking API uses Rest.

Because of that im planning to create a new repository for that. So it will be a different library. I hope you don't mind :-)

**Comment by wolfgangmauer** [comment]
Hmmm, try to see it from a user's point of view
I don't want to worry about which interface is used, that would be the 
great thing to simply start a tracking query via the client

Something like this:

$request = new \ChristophSchaeffer\Dhl\Request\tracking([trackingIds]);
$response = $client->tracking($request);



Am 09.06.2021 um 18:57 schrieb Christoph Schäffer:

**Comment by christoph-schaeffer** [comment]
I totally agree with you, but the thing is those 2 APIs work different, they also need different php extensions. If i woulf just need tracking for my Website i would need to install the PHP-Soap extension even though it is never used. 

I don't really think that using 2 composer packages would be more bothersome... 

Well if you have an exception or status message handler which is called for all functions it would be easier to have one client instead of 2, that's true.

It's actually not set in stone that i will make another repository. I will most likely think about that again when i start to work on the tracking api

**Comment by christoph-schaeffer** [comment]
I was also thinking about making a third package which abstracts those 2 otjer packages into one, aswell. But im not really sure if that is necessary...

**Comment by christoph-schaeffer** [comment]
Hello @wolfgangmauer,

After thinking about it for a while i came up with an architecture that would be clean and could have both tracking and shipping features in this library.

I will add the tracking feature in Q4 this year. 👍

best regards

**Comment by wolfgangmauer** [comment]
Perfect!

Am 24.07.2021 um 09:44 schrieb Christoph Schäffer:

**Comment by wolfgangmauer** [comment]
Has there already been any progress ?

**Comment by christoph-schaeffer** [comment]
Hello Wolfgang,

unfortunatly not yet, but like i've said at around Q4 it should be done. So the maximum would be december 31st.

**Comment by wolfgangmauer** [comment]
Hmmmmm ;-)

**Comment by christoph-schaeffer** [comment]
Hey @wolfgangmauer ,

yes you're right the deadline didn't work in the end...  But, im pretty far. You can check the commits on the develop branch. 

I'm thinking of splitting the Client class into 2 different Client classes because those 2 apis require different authentication parameters. Instead of the dhl business customer account name. For Tracking they want a "zT Kennung". What do you think? 2 Classes or a new optional parameter?

Im planning to finish in the next few days. However i can't promise anything...

I'll notify you here when its released 👍

**Comment by christoph-schaeffer** [comment]
@wolfgangmauer with version 3.2.0 tracking has been added.

Thanks for your support.

closing the issue.
